
development:
  adapter: postgresql
  encoding: unicode
  database: izvid33_development
  username: nikoo
  password: novadb
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: izvid33_test
  username: nikoo
  password: novadb
  host: localhost

production: 
  adapter: postgresql
  encoding: unicode
  database: izvid33_production
  password: <%= ENV['DATABASE_PASSWORD'] %>