development:
development:
  adapter: postgresql
  encoding: unicode
  database: izvid_development
  username: nikoo
  password: novadb
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: izvid_test
  username: nikoo
  password: novadb
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
