default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: izvid_dev

test:
  <<: *default
  database: izvid_test

production:
  url: <%= ENV["DATABASE_URL"] %>

