development:
development:
  adapter: postgresql
  encoding: unicode
  database: izvid_development
  username: nikoo
  password: novadb
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: izvid_test
  username: nikoo
  password: novadb
  host: localhost

production: 
  adapter: postgresql
  encoding: unicode
  database: izvid_production
  password: <%= ENV['DATABASE_PASSWORD'] %>